basePath: /api/v1
info:
  contact: {}
  description: This is a sample server celler server.
  title: NGLab API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
