definitions:
  handler.ResponseBody:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.Datetime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  model.Menu:
    properties:
      created_at:
        $ref: '#/definitions/model.Datetime'
      created_by:
        type: string
      enabled:
        type: boolean
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
      path:
        type: string
      sort:
        type: integer
      type:
        description: 0:目录 1:菜单 2:按钮
        type: integer
      updated_at:
        $ref: '#/definitions/model.Datetime'
      updated_by:
        type: string
    type: object
  model.MenuCreateRequest:
    properties:
      enabled:
        type: boolean
      icon:
        type: string
      name:
        type: string
      parent_id:
        description: 0:顶级菜单
        type: integer
      path:
        type: string
      sort:
        type: integer
      type:
        description: 0:目录 1:菜单 2:按钮
        type: integer
    type: object
  model.MenuTree:
    properties:
      children:
        items:
          $ref: '#/definitions/model.MenuTree'
        type: array
      created_at:
        $ref: '#/definitions/model.Datetime'
      created_by:
        type: string
      enabled:
        type: boolean
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
      path:
        type: string
      sort:
        type: integer
      type:
        description: 0:目录 1:菜单 2:按钮
        type: integer
      updated_at:
        $ref: '#/definitions/model.Datetime'
      updated_by:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterResponse:
    properties:
      id:
        type: integer
    type: object
  model.User:
    properties:
      avatar_url:
        type: string
      created_at:
        $ref: '#/definitions/model.Datetime'
      created_by:
        type: string
      email:
        type: string
      enabled:
        type: integer
      id:
        type: integer
      phone:
        type: string
      real_name:
        type: string
      type:
        type: integer
      updated_at:
        $ref: '#/definitions/model.Datetime'
      updated_by:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
      summary: Login user
      tags:
      - Auth
  /menus:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.MenuTree'
                  type: array
              type: object
      tags:
      - Menu
    post:
      parameters:
      - description: Menu request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.MenuCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Menu'
                  type: array
              type: object
      tags:
      - Menu
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/model.RegisterResponse'
              type: object
      summary: Register user
      tags:
      - Auth
  /user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      summary: Get auth user
      tags:
      - Auth
  /users/{id}:
    get:
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      summary: User Get By ID
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
